# Generated by Django 2.1.15 on 2020-08-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='testimage',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
