# Generated by Django 2.1.15 on 2020-08-04 06:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200804_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.ImageField(upload_to=app.models.f),
        ),
    ]
