# Generated by Django 2.1.15 on 2020-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testimage_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='real_label',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
