# Generated by Django 2.1.15 on 2020-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200804_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='real_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
